//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMSReporting
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_rpt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer_rpt()
        {
            this.order_rpt = new HashSet<order_rpt>();
        }
    
        public int customer_id { get; set; }
        public string customer_name { get; set; }
        public Nullable<System.DateTime> setup_date { get; set; }
        public Nullable<int> setup_by { get; set; }
        public string status_code { get; set; }
        public string ship_to_bill_ind { get; set; }
        public string website_url { get; set; }
        public string account_number { get; set; }
        public string override_validation_ind { get; set; }
        public Nullable<long> parent_id { get; set; }
        public string parent_ind { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_rpt> order_rpt { get; set; }
    }
}
