//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMSReporting
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ReportingEntities : DbContext
    {
        public ReportingEntities()
            : base("name=ReportingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<order_rpt> order_rpt { get; set; }
        public virtual DbSet<order_payments_rpt> order_payments_rpt { get; set; }
        public virtual DbSet<customer_rpt> customers_rpt { get; set; }
        public virtual DbSet<vw_order_payments> vw_order_payments { get; set; }
        public virtual DbSet<vw_order_quantities> vw_order_quantities { get; set; }
        public virtual DbSet<vw_order_quantities_rollup> vw_order_quantities_rollup { get; set; }
    
        public virtual ObjectResult<sp_get_order_quantities_Result> sp_get_order_quantities()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_order_quantities_Result>("sp_get_order_quantities");
        }
    }
}
