//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMSReporting
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_order_quantities_rollup
    {
        public int id { get; set; }
        public Nullable<System.DateTime> order_due_date { get; set; }
        public Nullable<int> garments_only { get; set; }
        public Nullable<int> screen_prints { get; set; }
        public Nullable<int> screen_prints_reorder { get; set; }
        public Nullable<int> embroidery { get; set; }
        public Nullable<int> embroidery_reorder { get; set; }
        public Nullable<int> laser_engraving { get; set; }
        public Nullable<int> ad_specialty { get; set; }
        public Nullable<int> TOTAL_QTY { get; set; }
    }
}
