//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMSEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class correspondence
    {
        public int correspondence_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<System.DateTime> corr_date { get; set; }
        public string corr_type { get; set; }
        public string corr_disp { get; set; }
        public Nullable<int> user_id { get; set; }
        public string corr_filename { get; set; }
    
        public virtual customer customers { get; set; }
    }
}
