
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIMSEntities
{

using System;
    using System.Collections.Generic;
    
public partial class customer_notes
{

    public int customer_notes_id { get; set; }

    public Nullable<int> customer_id { get; set; }

    public Nullable<int> user_id { get; set; }

    public Nullable<System.DateTime> entered_date { get; set; }

    public string notes_value { get; set; }

    public string private_ind { get; set; }

}

}
