
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIMSEntities
{

using System;
    using System.Collections.Generic;
    
public partial class navigation
{

    public int navigation_id { get; set; }

    public string name { get; set; }

    public string tooltip { get; set; }

    public string current_product { get; set; }

    public string start_product { get; set; }

    public string url { get; set; }

    public string invalid_redirect { get; set; }

    public Nullable<int> order_by { get; set; }

}

}
