//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMSEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_colors
    {
        public int order_color_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public string order_by { get; set; }
        public string manufacturer { get; set; }
        public string color_code { get; set; }
        public string color_description { get; set; }
    }
}
