//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMSEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_art_file
    {
        public long order_art_id { get; set; }
        public Nullable<long> order_id { get; set; }
        public Nullable<int> order_by { get; set; }
        public string image_file { get; set; }
        public string art_folder { get; set; }
        public string note { get; set; }
    }
}
