//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMSEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_order_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vw_order_info()
        {
            this.order_task = new HashSet<order_task>();
        }
    
        public int order_id { get; set; }
        public string order_number { get; set; }
        public string order_status { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<System.DateTime> order_due_date { get; set; }
        public string order_type { get; set; }
        public string contact { get; set; }
        public string customer_name { get; set; }
        public long ItemCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_task> order_task { get; set; }
    }
}
